// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ2xHKMELfb2FDJ6J4Rv6ZRYIjjG7Xb-w',
    appId: '1:819704525380:web:572acc9af02cd0fdefc211',
    messagingSenderId: '819704525380',
    projectId: 'fir-initialize',
    authDomain: 'fir-initialize.firebaseapp.com',
    storageBucket: 'fir-initialize.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCad5yS6NteMdmZBSmEgce5Dvi8WQGi_fI',
    appId: '1:819704525380:android:712145614b949f5fefc211',
    messagingSenderId: '819704525380',
    projectId: 'fir-initialize',
    storageBucket: 'fir-initialize.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMTP7tlCheOvGvEdQThD-bicJRaA9TMf4',
    appId: '1:819704525380:ios:20642b7294dcd7ceefc211',
    messagingSenderId: '819704525380',
    projectId: 'fir-initialize',
    storageBucket: 'fir-initialize.appspot.com',
    iosClientId: '819704525380-asktor3podnprdlskir6ekjnp3tvdj88.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest18',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMTP7tlCheOvGvEdQThD-bicJRaA9TMf4',
    appId: '1:819704525380:ios:20642b7294dcd7ceefc211',
    messagingSenderId: '819704525380',
    projectId: 'fir-initialize',
    storageBucket: 'fir-initialize.appspot.com',
    iosClientId: '819704525380-asktor3podnprdlskir6ekjnp3tvdj88.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest18',
  );
}
